include: package:very_good_analysis/analysis_options.yaml

linter:
  rules:
    always_specify_types: true
    lines_longer_than_80_chars: false
    omit_local_variable_types: false
    public_member_api_docs: false

analyzer:
  plugins:
    - custom_lint
